//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.24 at 05:03:26 ÏÂÎç CST 
//


package test.jaxb;

import javax.xml.bind.annotation.XmlRegistry;
import test.jaxb.BookType.Authors;
import test.jaxb.BookType.Promotion;
import test.jaxb.Collection.Books;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the test.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: test.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Books }
     * 
     */
    public Books createCollectionBooks() {
        return new Books();
    }

    /**
     * Create an instance of {@link Promotion }
     * 
     */
    public Promotion createBookTypePromotion() {
        return new Promotion();
    }

    /**
     * Create an instance of {@link BookType }
     * 
     */
    public BookType createBookType() {
        return new BookType();
    }

    /**
     * Create an instance of {@link Authors }
     * 
     */
    public Authors createBookTypeAuthors() {
        return new Authors();
    }

    /**
     * Create an instance of {@link Collection }
     * 
     */
    public Collection createCollection() {
        return new Collection();
    }

}
