//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//


package com.chinatelecom.www.crm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 帐户类型
 * 
 * <p>Java class for ACCOUNT_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACCOUNT_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ACCOUNT_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CUST_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="COMMON_REGION_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ACCOUNT_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ACCOUNT_AREA_GRADE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ACCOUNT_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GROUP_PAY_METHOD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PAY_CYCLE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CONTACT_PHONE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MOBILE_PHONE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IF_DEFAULT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STATUS_CD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STATUS_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EXT_ACCOUNT_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LAN_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACCOUNT_TYPE", propOrder = {
    "accountid",
    "custid",
    "commonregionid",
    "accountname",
    "accountareagrade",
    "accountnumber",
    "grouppaymethod",
    "paycycle",
    "contactphone",
    "mobilephone",
    "ifdefault",
    "statuscd",
    "statusdate",
    "extaccountid",
    "lanid"
})
public class ACCOUNTTYPE {

    @XmlElement(name = "ACCOUNT_ID", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected String accountid;
    @XmlElement(name = "CUST_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custid;
    @XmlElement(name = "COMMON_REGION_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String commonregionid;
    @XmlElement(name = "ACCOUNT_NAME", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String accountname;
    @XmlElement(name = "ACCOUNT_AREA_GRADE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String accountareagrade;
    @XmlElement(name = "ACCOUNT_NUMBER", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String accountnumber;
    @XmlElement(name = "GROUP_PAY_METHOD", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String grouppaymethod;
    @XmlElement(name = "PAY_CYCLE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String paycycle;
    @XmlElement(name = "CONTACT_PHONE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String contactphone;
    @XmlElement(name = "MOBILE_PHONE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String mobilephone;
    @XmlElement(name = "IF_DEFAULT", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String ifdefault;
    @XmlElement(name = "STATUS_CD", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String statuscd;
    @XmlElement(name = "STATUS_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String statusdate;
    @XmlElement(name = "EXT_ACCOUNT_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String extaccountid;
    @XmlElement(name = "LAN_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String lanid;

    /**
     * Gets the value of the accountid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCOUNTID() {
        return accountid;
    }

    /**
     * Sets the value of the accountid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCOUNTID(String value) {
        this.accountid = value;
    }

    /**
     * Gets the value of the custid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTID() {
        return custid;
    }

    /**
     * Sets the value of the custid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTID(String value) {
        this.custid = value;
    }

    /**
     * Gets the value of the commonregionid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMMONREGIONID() {
        return commonregionid;
    }

    /**
     * Sets the value of the commonregionid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMMONREGIONID(String value) {
        this.commonregionid = value;
    }

    /**
     * Gets the value of the accountname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCOUNTNAME() {
        return accountname;
    }

    /**
     * Sets the value of the accountname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCOUNTNAME(String value) {
        this.accountname = value;
    }

    /**
     * Gets the value of the accountareagrade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCOUNTAREAGRADE() {
        return accountareagrade;
    }

    /**
     * Sets the value of the accountareagrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCOUNTAREAGRADE(String value) {
        this.accountareagrade = value;
    }

    /**
     * Gets the value of the accountnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCOUNTNUMBER() {
        return accountnumber;
    }

    /**
     * Sets the value of the accountnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCOUNTNUMBER(String value) {
        this.accountnumber = value;
    }

    /**
     * Gets the value of the grouppaymethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGROUPPAYMETHOD() {
        return grouppaymethod;
    }

    /**
     * Sets the value of the grouppaymethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGROUPPAYMETHOD(String value) {
        this.grouppaymethod = value;
    }

    /**
     * Gets the value of the paycycle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYCYCLE() {
        return paycycle;
    }

    /**
     * Sets the value of the paycycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYCYCLE(String value) {
        this.paycycle = value;
    }

    /**
     * Gets the value of the contactphone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTACTPHONE() {
        return contactphone;
    }

    /**
     * Sets the value of the contactphone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTACTPHONE(String value) {
        this.contactphone = value;
    }

    /**
     * Gets the value of the mobilephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOBILEPHONE() {
        return mobilephone;
    }

    /**
     * Sets the value of the mobilephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOBILEPHONE(String value) {
        this.mobilephone = value;
    }

    /**
     * Gets the value of the ifdefault property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIFDEFAULT() {
        return ifdefault;
    }

    /**
     * Sets the value of the ifdefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIFDEFAULT(String value) {
        this.ifdefault = value;
    }

    /**
     * Gets the value of the statuscd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSCD() {
        return statuscd;
    }

    /**
     * Sets the value of the statuscd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSCD(String value) {
        this.statuscd = value;
    }

    /**
     * Gets the value of the statusdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSDATE() {
        return statusdate;
    }

    /**
     * Sets the value of the statusdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSDATE(String value) {
        this.statusdate = value;
    }

    /**
     * Gets the value of the extaccountid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXTACCOUNTID() {
        return extaccountid;
    }

    /**
     * Sets the value of the extaccountid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXTACCOUNTID(String value) {
        this.extaccountid = value;
    }

    /**
     * Gets the value of the lanid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANID() {
        return lanid;
    }

    /**
     * Sets the value of the lanid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANID(String value) {
        this.lanid = value;
    }

}
