//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//


package com.chinatelecom.www.crm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 账单定制关系类型
 * 
 * <p>Java class for BILL_FORMAT_CUSTOMIZE_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BILL_FORMAT_CUSTOMIZE_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BILL_FORMAT_CUSTOMIZE_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ACCOUNT_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BILL_FORMAT_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BILL_POST_CYCLE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BILL_POST_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BILL_POST_CONTENT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="POST_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="POST_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EMAIL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BILL_FORMAT_CUSTOMIZE_TYPE", propOrder = {
    "billformatcustomizeid",
    "accountid",
    "billformatid",
    "custid",
    "billpostcycle",
    "billposttype",
    "billpostcontent",
    "postaddress",
    "postcode",
    "email"
})
public class BILLFORMATCUSTOMIZETYPE {

    @XmlElement(name = "BILL_FORMAT_CUSTOMIZE_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String billformatcustomizeid;
    @XmlElement(name = "ACCOUNT_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String accountid;
    @XmlElement(name = "BILL_FORMAT_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String billformatid;
    @XmlElement(name = "CUST_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custid;
    @XmlElement(name = "BILL_POST_CYCLE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String billpostcycle;
    @XmlElement(name = "BILL_POST_TYPE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String billposttype;
    @XmlElement(name = "BILL_POST_CONTENT", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String billpostcontent;
    @XmlElement(name = "POST_ADDRESS", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String postaddress;
    @XmlElement(name = "POST_CODE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String postcode;
    @XmlElement(name = "EMAIL", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String email;

    /**
     * Gets the value of the billformatcustomizeid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBILLFORMATCUSTOMIZEID() {
        return billformatcustomizeid;
    }

    /**
     * Sets the value of the billformatcustomizeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBILLFORMATCUSTOMIZEID(String value) {
        this.billformatcustomizeid = value;
    }

    /**
     * Gets the value of the accountid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCOUNTID() {
        return accountid;
    }

    /**
     * Sets the value of the accountid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCOUNTID(String value) {
        this.accountid = value;
    }

    /**
     * Gets the value of the billformatid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBILLFORMATID() {
        return billformatid;
    }

    /**
     * Sets the value of the billformatid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBILLFORMATID(String value) {
        this.billformatid = value;
    }

    /**
     * Gets the value of the custid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTID() {
        return custid;
    }

    /**
     * Sets the value of the custid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTID(String value) {
        this.custid = value;
    }

    /**
     * Gets the value of the billpostcycle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBILLPOSTCYCLE() {
        return billpostcycle;
    }

    /**
     * Sets the value of the billpostcycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBILLPOSTCYCLE(String value) {
        this.billpostcycle = value;
    }

    /**
     * Gets the value of the billposttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBILLPOSTTYPE() {
        return billposttype;
    }

    /**
     * Sets the value of the billposttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBILLPOSTTYPE(String value) {
        this.billposttype = value;
    }

    /**
     * Gets the value of the billpostcontent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBILLPOSTCONTENT() {
        return billpostcontent;
    }

    /**
     * Sets the value of the billpostcontent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBILLPOSTCONTENT(String value) {
        this.billpostcontent = value;
    }

    /**
     * Gets the value of the postaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSTADDRESS() {
        return postaddress;
    }

    /**
     * Sets the value of the postaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSTADDRESS(String value) {
        this.postaddress = value;
    }

    /**
     * Gets the value of the postcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSTCODE() {
        return postcode;
    }

    /**
     * Sets the value of the postcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSTCODE(String value) {
        this.postcode = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMAIL() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMAIL(String value) {
        this.email = value;
    }

}
