//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//

package com.chinatelecom.www.crm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.chinatelecom.www.crm.ContractRoot.SvcCont;

/**
 * 协议根对象
 * 
 * <p>Java class for ContractRoot complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContractRoot">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TcpCont" type="{http://www.chinatelecom.com/crm/comm/}TcpCont"/>
 *         &lt;element name="SvcCont" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SOO" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContractRoot", propOrder = { "tcpCont", "svcCont" })
@XmlRootElement(name = "ContractRoot")
public class ContractRoot {

	@XmlElement(name = "TcpCont", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
	protected TcpCont tcpCont;
	@XmlElement(name = "SvcCont", namespace = "http://www.chinatelecom.com/crm/comm/")
	protected SvcCont svcCont;

	/**
	 * Gets the value of the tcpCont property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link TcpCont }
	 *     
	 */
	public TcpCont getTcpCont() {
		return tcpCont;
	}

	/**
	 * Sets the value of the tcpCont property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link TcpCont }
	 *     
	 */
	public void setTcpCont(TcpCont value) {
		this.tcpCont = value;
	}

	/**
	 * Gets the value of the svcCont property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link SvcCont }
	 *     
	 */
	public SvcCont getSvcCont() {
		return svcCont;
	}

	/**
	 * Sets the value of the svcCont property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link SvcCont }
	 *     
	 */
	public void setSvcCont(SvcCont value) {
		this.svcCont = value;
	}

	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="SOO" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "soo" })
	public static class SvcCont {

		@XmlElement(name = "SOO", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
		protected List<Object> soo;

		/**
		 * Gets the value of the soo property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list,
		 * not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object.
		 * This is why there is not a <CODE>set</CODE> method for the soo property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * <pre>
		 *    getSOO().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Object }
		 * 
		 * 
		 */
		public List<Object> getSOO() {
			if (soo == null) {
				soo = new ArrayList<Object>();
			}
			return this.soo;
		}

	}

}
