//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//


package com.chinatelecom.www.crm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 客户信用额度类型
 * 
 * <p>Java class for CREDIT_LIMIT_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CREDIT_LIMIT_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CREDIT_LIMIT_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CUST_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CREDIT_OBJECT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CREDIT_OBJECT_ID" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="CREDIT_LIMIT_FEE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVALABLE_CREDIT_LIMIT_FEE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CREDIT_LIMIT_TYPE", propOrder = {
    "creditlimitid",
    "custid",
    "creditobject",
    "creditobjectid",
    "creditlimitfee",
    "avalablecreditlimitfee"
})
public class CREDITLIMITTYPE {

    @XmlElement(name = "CREDIT_LIMIT_ID", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected String creditlimitid;
    @XmlElement(name = "CUST_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custid;
    @XmlElement(name = "CREDIT_OBJECT", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String creditobject;
    @XmlElement(name = "CREDIT_OBJECT_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected Object creditobjectid;
    @XmlElement(name = "CREDIT_LIMIT_FEE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String creditlimitfee;
    @XmlElement(name = "AVALABLE_CREDIT_LIMIT_FEE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String avalablecreditlimitfee;

    /**
     * Gets the value of the creditlimitid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREDITLIMITID() {
        return creditlimitid;
    }

    /**
     * Sets the value of the creditlimitid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREDITLIMITID(String value) {
        this.creditlimitid = value;
    }

    /**
     * Gets the value of the custid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTID() {
        return custid;
    }

    /**
     * Sets the value of the custid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTID(String value) {
        this.custid = value;
    }

    /**
     * Gets the value of the creditobject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREDITOBJECT() {
        return creditobject;
    }

    /**
     * Sets the value of the creditobject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREDITOBJECT(String value) {
        this.creditobject = value;
    }

    /**
     * Gets the value of the creditobjectid property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCREDITOBJECTID() {
        return creditobjectid;
    }

    /**
     * Sets the value of the creditobjectid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCREDITOBJECTID(Object value) {
        this.creditobjectid = value;
    }

    /**
     * Gets the value of the creditlimitfee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREDITLIMITFEE() {
        return creditlimitfee;
    }

    /**
     * Sets the value of the creditlimitfee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREDITLIMITFEE(String value) {
        this.creditlimitfee = value;
    }

    /**
     * Gets the value of the avalablecreditlimitfee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVALABLECREDITLIMITFEE() {
        return avalablecreditlimitfee;
    }

    /**
     * Sets the value of the avalablecreditlimitfee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVALABLECREDITLIMITFEE(String value) {
        this.avalablecreditlimitfee = value;
    }

}
