//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//


package com.chinatelecom.www.crm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 俱乐部成员类型
 * 
 * <p>Java class for CUST_CLUB_MEMBER_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CUST_CLUB_MEMBER_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MEMBER_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CUST_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MEMBER_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MEMBER_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MEMBER_LEVEL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ID_CARD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PASSWORD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ASSESS_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EXP_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EFF_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ENTER_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STATE_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CREATE_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MODIFY_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ACTION_TYPE" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CUST_CLUB_MEMBER_TYPE", propOrder = {
    "memberid",
    "custid",
    "membercode",
    "membername",
    "memberlevel",
    "idcard",
    "password",
    "assessdate",
    "expdate",
    "effdate",
    "enterdate",
    "state",
    "statedate",
    "createdate",
    "modifydate"
})
public class CUSTCLUBMEMBERTYPE {

    @XmlElement(name = "MEMBER_ID", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected String memberid;
    @XmlElement(name = "CUST_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custid;
    @XmlElement(name = "MEMBER_CODE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String membercode;
    @XmlElement(name = "MEMBER_NAME", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String membername;
    @XmlElement(name = "MEMBER_LEVEL", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String memberlevel;
    @XmlElement(name = "ID_CARD", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String idcard;
    @XmlElement(name = "PASSWORD", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String password;
    @XmlElement(name = "ASSESS_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String assessdate;
    @XmlElement(name = "EXP_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String expdate;
    @XmlElement(name = "EFF_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String effdate;
    @XmlElement(name = "ENTER_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String enterdate;
    @XmlElement(name = "STATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String state;
    @XmlElement(name = "STATE_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String statedate;
    @XmlElement(name = "CREATE_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String createdate;
    @XmlElement(name = "MODIFY_DATE", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected String modifydate;
    @XmlAttribute(name = "ACTION_TYPE")
    protected String actiontype;

    /**
     * Gets the value of the memberid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEMBERID() {
        return memberid;
    }

    /**
     * Sets the value of the memberid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEMBERID(String value) {
        this.memberid = value;
    }

    /**
     * Gets the value of the custid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTID() {
        return custid;
    }

    /**
     * Sets the value of the custid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTID(String value) {
        this.custid = value;
    }

    /**
     * Gets the value of the membercode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEMBERCODE() {
        return membercode;
    }

    /**
     * Sets the value of the membercode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEMBERCODE(String value) {
        this.membercode = value;
    }

    /**
     * Gets the value of the membername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEMBERNAME() {
        return membername;
    }

    /**
     * Sets the value of the membername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEMBERNAME(String value) {
        this.membername = value;
    }

    /**
     * Gets the value of the memberlevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEMBERLEVEL() {
        return memberlevel;
    }

    /**
     * Sets the value of the memberlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEMBERLEVEL(String value) {
        this.memberlevel = value;
    }

    /**
     * Gets the value of the idcard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDCARD() {
        return idcard;
    }

    /**
     * Sets the value of the idcard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDCARD(String value) {
        this.idcard = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPASSWORD() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPASSWORD(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the assessdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getASSESSDATE() {
        return assessdate;
    }

    /**
     * Sets the value of the assessdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setASSESSDATE(String value) {
        this.assessdate = value;
    }

    /**
     * Gets the value of the expdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPDATE() {
        return expdate;
    }

    /**
     * Sets the value of the expdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPDATE(String value) {
        this.expdate = value;
    }

    /**
     * Gets the value of the effdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEFFDATE() {
        return effdate;
    }

    /**
     * Sets the value of the effdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEFFDATE(String value) {
        this.effdate = value;
    }

    /**
     * Gets the value of the enterdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENTERDATE() {
        return enterdate;
    }

    /**
     * Sets the value of the enterdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENTERDATE(String value) {
        this.enterdate = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATE() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATE(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the statedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATEDATE() {
        return statedate;
    }

    /**
     * Sets the value of the statedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATEDATE(String value) {
        this.statedate = value;
    }

    /**
     * Gets the value of the createdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATEDATE() {
        return createdate;
    }

    /**
     * Sets the value of the createdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATEDATE(String value) {
        this.createdate = value;
    }

    /**
     * Gets the value of the modifydate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMODIFYDATE() {
        return modifydate;
    }

    /**
     * Sets the value of the modifydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMODIFYDATE(String value) {
        this.modifydate = value;
    }

    /**
     * Gets the value of the actiontype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTIONTYPE() {
        return actiontype;
    }

    /**
     * Sets the value of the actiontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTIONTYPE(String value) {
        this.actiontype = value;
    }

}
