//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//


package com.chinatelecom.www.crm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.chinatelecom.www.crm.CUSTTYPEUP.CUSTCONTACTINFO;


/**
 * 客户类型类型(数据上传用)
 * 
 * <p>Java class for CUST_TYPE_UP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CUST_TYPE_UP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CUST_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CUST_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GROUP_CUST_SEQ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_AREA_GRADE" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="CUST_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ENGLISH_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_SUB_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_BRAND" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="COMMON_REGION_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IMPORTANT_LEVEL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_GRADE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SERVICE_LEVEL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CREDIT_LEVEL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INDUSTY_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_PWD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STATE_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ENTER_DATE" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="CREATE_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_CERT" type="{http://www.chinatelecom.com/crm/comm/}CUST_CERT_TYPE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CUST_CONTACT_INFO" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.chinatelecom.com/crm/comm/}CUST_CONTACT_INFO_TYPE">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CUST_ATTR" type="{http://www.chinatelecom.com/crm/comm/}CUST_ATTR_TYPE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CUST_REL" type="{http://www.chinatelecom.com/crm/comm/}CUST_REL_TYPE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MODIFY_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ACTION_TYPE" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CUST_TYPE_UP", propOrder = {
    "custid",
    "custnumber",
    "groupcustseq",
    "custareagrade",
    "custname",
    "englishname",
    "custaddress",
    "custtype",
    "custsubtype",
    "custbrand",
    "commonregionid",
    "importantlevel",
    "custgrade",
    "servicelevel",
    "creditlevel",
    "industycode",
    "custpwd",
    "state",
    "statedate",
    "enterdate",
    "createdate",
    "custcert",
    "custcontactinfo",
    "custattr",
    "custrel",
    "modifydate"
})
public class CUSTTYPEUP {

    @XmlElement(name = "CUST_ID", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected String custid;
    @XmlElement(name = "CUST_NUMBER", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custnumber;
    @XmlElement(name = "GROUP_CUST_SEQ", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String groupcustseq;
    @XmlElement(name = "CUST_AREA_GRADE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected Object custareagrade;
    @XmlElement(name = "CUST_NAME", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custname;
    @XmlElement(name = "ENGLISH_NAME", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String englishname;
    @XmlElement(name = "CUST_ADDRESS", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custaddress;
    @XmlElement(name = "CUST_TYPE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custtype;
    @XmlElement(name = "CUST_SUB_TYPE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custsubtype;
    @XmlElement(name = "CUST_BRAND", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custbrand;
    @XmlElement(name = "COMMON_REGION_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String commonregionid;
    @XmlElement(name = "IMPORTANT_LEVEL", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String importantlevel;
    @XmlElement(name = "CUST_GRADE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custgrade;
    @XmlElement(name = "SERVICE_LEVEL", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String servicelevel;
    @XmlElement(name = "CREDIT_LEVEL", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String creditlevel;
    @XmlElement(name = "INDUSTY_CODE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String industycode;
    @XmlElement(name = "CUST_PWD", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custpwd;
    @XmlElement(name = "STATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String state;
    @XmlElement(name = "STATE_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String statedate;
    @XmlElement(name = "ENTER_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected Object enterdate;
    @XmlElement(name = "CREATE_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String createdate;
    @XmlElement(name = "CUST_CERT", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected List<CUSTCERTTYPE> custcert;
    @XmlElement(name = "CUST_CONTACT_INFO", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected List<CUSTCONTACTINFO> custcontactinfo;
    @XmlElement(name = "CUST_ATTR", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected List<CUSTATTRTYPE> custattr;
    @XmlElement(name = "CUST_REL", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected List<CUSTRELTYPE> custrel;
    @XmlElement(name = "MODIFY_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String modifydate;
    @XmlAttribute(name = "ACTION_TYPE")
    protected String actiontype;

    /**
     * Gets the value of the custid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTID() {
        return custid;
    }

    /**
     * Sets the value of the custid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTID(String value) {
        this.custid = value;
    }

    /**
     * Gets the value of the custnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTNUMBER() {
        return custnumber;
    }

    /**
     * Sets the value of the custnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTNUMBER(String value) {
        this.custnumber = value;
    }

    /**
     * Gets the value of the groupcustseq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGROUPCUSTSEQ() {
        return groupcustseq;
    }

    /**
     * Sets the value of the groupcustseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGROUPCUSTSEQ(String value) {
        this.groupcustseq = value;
    }

    /**
     * Gets the value of the custareagrade property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCUSTAREAGRADE() {
        return custareagrade;
    }

    /**
     * Sets the value of the custareagrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCUSTAREAGRADE(Object value) {
        this.custareagrade = value;
    }

    /**
     * Gets the value of the custname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTNAME() {
        return custname;
    }

    /**
     * Sets the value of the custname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTNAME(String value) {
        this.custname = value;
    }

    /**
     * Gets the value of the englishname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENGLISHNAME() {
        return englishname;
    }

    /**
     * Sets the value of the englishname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENGLISHNAME(String value) {
        this.englishname = value;
    }

    /**
     * Gets the value of the custaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTADDRESS() {
        return custaddress;
    }

    /**
     * Sets the value of the custaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTADDRESS(String value) {
        this.custaddress = value;
    }

    /**
     * Gets the value of the custtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTTYPE() {
        return custtype;
    }

    /**
     * Sets the value of the custtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTTYPE(String value) {
        this.custtype = value;
    }

    /**
     * Gets the value of the custsubtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTSUBTYPE() {
        return custsubtype;
    }

    /**
     * Sets the value of the custsubtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTSUBTYPE(String value) {
        this.custsubtype = value;
    }

    /**
     * Gets the value of the custbrand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTBRAND() {
        return custbrand;
    }

    /**
     * Sets the value of the custbrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTBRAND(String value) {
        this.custbrand = value;
    }

    /**
     * Gets the value of the commonregionid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMMONREGIONID() {
        return commonregionid;
    }

    /**
     * Sets the value of the commonregionid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMMONREGIONID(String value) {
        this.commonregionid = value;
    }

    /**
     * Gets the value of the importantlevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMPORTANTLEVEL() {
        return importantlevel;
    }

    /**
     * Sets the value of the importantlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMPORTANTLEVEL(String value) {
        this.importantlevel = value;
    }

    /**
     * Gets the value of the custgrade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTGRADE() {
        return custgrade;
    }

    /**
     * Sets the value of the custgrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTGRADE(String value) {
        this.custgrade = value;
    }

    /**
     * Gets the value of the servicelevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERVICELEVEL() {
        return servicelevel;
    }

    /**
     * Sets the value of the servicelevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERVICELEVEL(String value) {
        this.servicelevel = value;
    }

    /**
     * Gets the value of the creditlevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREDITLEVEL() {
        return creditlevel;
    }

    /**
     * Sets the value of the creditlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREDITLEVEL(String value) {
        this.creditlevel = value;
    }

    /**
     * Gets the value of the industycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINDUSTYCODE() {
        return industycode;
    }

    /**
     * Sets the value of the industycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINDUSTYCODE(String value) {
        this.industycode = value;
    }

    /**
     * Gets the value of the custpwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTPWD() {
        return custpwd;
    }

    /**
     * Sets the value of the custpwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTPWD(String value) {
        this.custpwd = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATE() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATE(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the statedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATEDATE() {
        return statedate;
    }

    /**
     * Sets the value of the statedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATEDATE(String value) {
        this.statedate = value;
    }

    /**
     * Gets the value of the enterdate property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getENTERDATE() {
        return enterdate;
    }

    /**
     * Sets the value of the enterdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setENTERDATE(Object value) {
        this.enterdate = value;
    }

    /**
     * Gets the value of the createdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATEDATE() {
        return createdate;
    }

    /**
     * Sets the value of the createdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATEDATE(String value) {
        this.createdate = value;
    }

    /**
     * Gets the value of the custcert property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the custcert property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCUSTCERT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CUSTCERTTYPE }
     * 
     * 
     */
    public List<CUSTCERTTYPE> getCUSTCERT() {
        if (custcert == null) {
            custcert = new ArrayList<CUSTCERTTYPE>();
        }
        return this.custcert;
    }

    /**
     * Gets the value of the custcontactinfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the custcontactinfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCUSTCONTACTINFO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CUSTCONTACTINFO }
     * 
     * 
     */
    public List<CUSTCONTACTINFO> getCUSTCONTACTINFO() {
        if (custcontactinfo == null) {
            custcontactinfo = new ArrayList<CUSTCONTACTINFO>();
        }
        return this.custcontactinfo;
    }

    /**
     * Gets the value of the custattr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the custattr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCUSTATTR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CUSTATTRTYPE }
     * 
     * 
     */
    public List<CUSTATTRTYPE> getCUSTATTR() {
        if (custattr == null) {
            custattr = new ArrayList<CUSTATTRTYPE>();
        }
        return this.custattr;
    }

    /**
     * Gets the value of the custrel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the custrel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCUSTREL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CUSTRELTYPE }
     * 
     * 
     */
    public List<CUSTRELTYPE> getCUSTREL() {
        if (custrel == null) {
            custrel = new ArrayList<CUSTRELTYPE>();
        }
        return this.custrel;
    }

    /**
     * Gets the value of the modifydate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMODIFYDATE() {
        return modifydate;
    }

    /**
     * Sets the value of the modifydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMODIFYDATE(String value) {
        this.modifydate = value;
    }

    /**
     * Gets the value of the actiontype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTIONTYPE() {
        return actiontype;
    }

    /**
     * Sets the value of the actiontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTIONTYPE(String value) {
        this.actiontype = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.chinatelecom.com/crm/comm/}CUST_CONTACT_INFO_TYPE">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CUSTCONTACTINFO
        extends CUSTCONTACTINFOTYPE
    {


    }

}
