//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//


package com.chinatelecom.www.crm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 客户证件
 * 
 * <p>Java class for CUST_CERT_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CUST_CERT_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CUST_CERTI_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CUST_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CERTI_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CERT_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CERT_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CERT_ORG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EFF_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EXP_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CREATE_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CUST_CERT_TYPE", propOrder = {
    "custcertiid",
    "custid",
    "certitype",
    "certnumber",
    "certaddress",
    "certorg",
    "effdate",
    "expdate",
    "createdate"
})
public class CUSTCERTTYPE {

    @XmlElement(name = "CUST_CERTI_ID", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected String custcertiid;
    @XmlElement(name = "CUST_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custid;
    @XmlElement(name = "CERTI_TYPE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String certitype;
    @XmlElement(name = "CERT_NUMBER", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String certnumber;
    @XmlElement(name = "CERT_ADDRESS", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String certaddress;
    @XmlElement(name = "CERT_ORG", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String certorg;
    @XmlElement(name = "EFF_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String effdate;
    @XmlElement(name = "EXP_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String expdate;
    @XmlElement(name = "CREATE_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String createdate;

    /**
     * Gets the value of the custcertiid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTCERTIID() {
        return custcertiid;
    }

    /**
     * Sets the value of the custcertiid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTCERTIID(String value) {
        this.custcertiid = value;
    }

    /**
     * Gets the value of the custid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTID() {
        return custid;
    }

    /**
     * Sets the value of the custid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTID(String value) {
        this.custid = value;
    }

    /**
     * Gets the value of the certitype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCERTITYPE() {
        return certitype;
    }

    /**
     * Sets the value of the certitype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCERTITYPE(String value) {
        this.certitype = value;
    }

    /**
     * Gets the value of the certnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCERTNUMBER() {
        return certnumber;
    }

    /**
     * Sets the value of the certnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCERTNUMBER(String value) {
        this.certnumber = value;
    }

    /**
     * Gets the value of the certaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCERTADDRESS() {
        return certaddress;
    }

    /**
     * Sets the value of the certaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCERTADDRESS(String value) {
        this.certaddress = value;
    }

    /**
     * Gets the value of the certorg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCERTORG() {
        return certorg;
    }

    /**
     * Sets the value of the certorg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCERTORG(String value) {
        this.certorg = value;
    }

    /**
     * Gets the value of the effdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEFFDATE() {
        return effdate;
    }

    /**
     * Sets the value of the effdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEFFDATE(String value) {
        this.effdate = value;
    }

    /**
     * Gets the value of the expdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPDATE() {
        return expdate;
    }

    /**
     * Sets the value of the expdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPDATE(String value) {
        this.expdate = value;
    }

    /**
     * Gets the value of the createdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATEDATE() {
        return createdate;
    }

    /**
     * Sets the value of the createdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATEDATE(String value) {
        this.createdate = value;
    }

}
