//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 ÏÂÎç CST 
//


package com.chinatelecom.www.crm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ¿Í»§
 * 
 * <p>Java class for CUST_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CUST_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CUST_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CUST_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GROUP_CUST_SEQ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_SUB_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_BRAND" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="COMMON_REGION_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LAN_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_AREA_GRADE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SERVICE_LEVEL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CREDIT_LEVEL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INDUSTRY_CD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_PWD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STATUS_CD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STATUS_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ENTER_DATE" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="CREATE_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CUST_TYPE", propOrder = {
    "custid",
    "custnumber",
    "groupcustseq",
    "custname",
    "custaddress",
    "custtype",
    "custsubtype",
    "custbrand",
    "commonregionid",
    "lanid",
    "custareagrade",
    "servicelevel",
    "creditlevel",
    "industrycd",
    "custpwd",
    "statuscd",
    "statusdate",
    "enterdate",
    "createdate"
})
public class CUSTTYPE {

    @XmlElement(name = "CUST_ID", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected String custid;
    @XmlElement(name = "CUST_NUMBER", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custnumber;
    @XmlElement(name = "GROUP_CUST_SEQ", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String groupcustseq;
    @XmlElement(name = "CUST_NAME", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custname;
    @XmlElement(name = "CUST_ADDRESS", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custaddress;
    @XmlElement(name = "CUST_TYPE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custtype;
    @XmlElement(name = "CUST_SUB_TYPE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custsubtype;
    @XmlElement(name = "CUST_BRAND", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custbrand;
    @XmlElement(name = "COMMON_REGION_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String commonregionid;
    @XmlElement(name = "LAN_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String lanid;
    @XmlElement(name = "CUST_AREA_GRADE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custareagrade;
    @XmlElement(name = "SERVICE_LEVEL", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String servicelevel;
    @XmlElement(name = "CREDIT_LEVEL", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String creditlevel;
    @XmlElement(name = "INDUSTRY_CD", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String industrycd;
    @XmlElement(name = "CUST_PWD", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custpwd;
    @XmlElement(name = "STATUS_CD", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String statuscd;
    @XmlElement(name = "STATUS_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String statusdate;
    @XmlElement(name = "ENTER_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected Object enterdate;
    @XmlElement(name = "CREATE_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String createdate;

    /**
     * Gets the value of the custid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTID() {
        return custid;
    }

    /**
     * Sets the value of the custid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTID(String value) {
        this.custid = value;
    }

    /**
     * Gets the value of the custnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTNUMBER() {
        return custnumber;
    }

    /**
     * Sets the value of the custnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTNUMBER(String value) {
        this.custnumber = value;
    }

    /**
     * Gets the value of the groupcustseq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGROUPCUSTSEQ() {
        return groupcustseq;
    }

    /**
     * Sets the value of the groupcustseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGROUPCUSTSEQ(String value) {
        this.groupcustseq = value;
    }

    /**
     * Gets the value of the custname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTNAME() {
        return custname;
    }

    /**
     * Sets the value of the custname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTNAME(String value) {
        this.custname = value;
    }

    /**
     * Gets the value of the custaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTADDRESS() {
        return custaddress;
    }

    /**
     * Sets the value of the custaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTADDRESS(String value) {
        this.custaddress = value;
    }

    /**
     * Gets the value of the custtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTTYPE() {
        return custtype;
    }

    /**
     * Sets the value of the custtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTTYPE(String value) {
        this.custtype = value;
    }

    /**
     * Gets the value of the custsubtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTSUBTYPE() {
        return custsubtype;
    }

    /**
     * Sets the value of the custsubtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTSUBTYPE(String value) {
        this.custsubtype = value;
    }

    /**
     * Gets the value of the custbrand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTBRAND() {
        return custbrand;
    }

    /**
     * Sets the value of the custbrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTBRAND(String value) {
        this.custbrand = value;
    }

    /**
     * Gets the value of the commonregionid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMMONREGIONID() {
        return commonregionid;
    }

    /**
     * Sets the value of the commonregionid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMMONREGIONID(String value) {
        this.commonregionid = value;
    }

    /**
     * Gets the value of the lanid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANID() {
        return lanid;
    }

    /**
     * Sets the value of the lanid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANID(String value) {
        this.lanid = value;
    }

    /**
     * Gets the value of the custareagrade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTAREAGRADE() {
        return custareagrade;
    }

    /**
     * Sets the value of the custareagrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTAREAGRADE(String value) {
        this.custareagrade = value;
    }

    /**
     * Gets the value of the servicelevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERVICELEVEL() {
        return servicelevel;
    }

    /**
     * Sets the value of the servicelevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERVICELEVEL(String value) {
        this.servicelevel = value;
    }

    /**
     * Gets the value of the creditlevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREDITLEVEL() {
        return creditlevel;
    }

    /**
     * Sets the value of the creditlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREDITLEVEL(String value) {
        this.creditlevel = value;
    }

    /**
     * Gets the value of the industrycd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINDUSTRYCD() {
        return industrycd;
    }

    /**
     * Sets the value of the industrycd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINDUSTRYCD(String value) {
        this.industrycd = value;
    }

    /**
     * Gets the value of the custpwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTPWD() {
        return custpwd;
    }

    /**
     * Sets the value of the custpwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTPWD(String value) {
        this.custpwd = value;
    }

    /**
     * Gets the value of the statuscd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSCD() {
        return statuscd;
    }

    /**
     * Sets the value of the statuscd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSCD(String value) {
        this.statuscd = value;
    }

    /**
     * Gets the value of the statusdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSDATE() {
        return statusdate;
    }

    /**
     * Sets the value of the statusdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSDATE(String value) {
        this.statusdate = value;
    }

    /**
     * Gets the value of the enterdate property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getENTERDATE() {
        return enterdate;
    }

    /**
     * Sets the value of the enterdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setENTERDATE(Object value) {
        this.enterdate = value;
    }

    /**
     * Gets the value of the createdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATEDATE() {
        return createdate;
    }

    /**
     * Sets the value of the createdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATEDATE(String value) {
        this.createdate = value;
    }

}
