//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//


package com.chinatelecom.www.crm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 客户认证输入
 * 
 * <p>Java class for CUST_AUTHENTICATE_REQ_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CUST_AUTHENTICATE_REQ_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PUB_REQ" type="{http://www.chinatelecom.com/crm/comm/}PUB_REQ_TYPE"/>
 *         &lt;element name="AREA_NBR" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="AUTH_MOTHOD" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="AUTH_VALUE1" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="AUTH_VALUE2" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CUST_AUTHENTICATE_REQ_TYPE", propOrder = {
    "pubreq",
    "areanbr",
    "authmothod",
    "authvalue1",
    "authvalue2"
})
public class CUSTAUTHENTICATEREQTYPE {

    @XmlElement(name = "PUB_REQ", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected PUBREQTYPE pubreq;
    @XmlElement(name = "AREA_NBR", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected Object areanbr;
    @XmlElement(name = "AUTH_MOTHOD", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected Object authmothod;
    @XmlElement(name = "AUTH_VALUE1", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected Object authvalue1;
    @XmlElement(name = "AUTH_VALUE2", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected Object authvalue2;

    /**
     * Gets the value of the pubreq property.
     * 
     * @return
     *     possible object is
     *     {@link PUBREQTYPE }
     *     
     */
    public PUBREQTYPE getPUBREQ() {
        return pubreq;
    }

    /**
     * Sets the value of the pubreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PUBREQTYPE }
     *     
     */
    public void setPUBREQ(PUBREQTYPE value) {
        this.pubreq = value;
    }

    /**
     * Gets the value of the areanbr property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAREANBR() {
        return areanbr;
    }

    /**
     * Sets the value of the areanbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAREANBR(Object value) {
        this.areanbr = value;
    }

    /**
     * Gets the value of the authmothod property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAUTHMOTHOD() {
        return authmothod;
    }

    /**
     * Sets the value of the authmothod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAUTHMOTHOD(Object value) {
        this.authmothod = value;
    }

    /**
     * Gets the value of the authvalue1 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAUTHVALUE1() {
        return authvalue1;
    }

    /**
     * Sets the value of the authvalue1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAUTHVALUE1(Object value) {
        this.authvalue1 = value;
    }

    /**
     * Gets the value of the authvalue2 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAUTHVALUE2() {
        return authvalue2;
    }

    /**
     * Sets the value of the authvalue2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAUTHVALUE2(Object value) {
        this.authvalue2 = value;
    }

}
