//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//


package com.chinatelecom.www.crm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.chinatelecom.www.crm.CUSTCLUBTYPE.CUSTCLUBMEMBER;


/**
 * 客户俱乐部类型
 * 
 * <p>Java class for CUST_CLUB_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CUST_CLUB_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CUST_CLUB_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CUST_CLUB_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_CLUB_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_CLUB_DESC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_CLUB_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EFF_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EXP_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STATE_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CREATE_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_CLUB_MEMBER" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.chinatelecom.com/crm/comm/}CUST_CLUB_MEMBER_TYPE">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MODIFY_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ACTION_TYPE" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CUST_CLUB_TYPE", propOrder = {
    "custclubid",
    "custclubcode",
    "custclubname",
    "custclubdesc",
    "custclubtype",
    "effdate",
    "expdate",
    "state",
    "statedate",
    "createdate",
    "custclubmember",
    "modifydate"
})
public class CUSTCLUBTYPE {

    @XmlElement(name = "CUST_CLUB_ID", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected String custclubid;
    @XmlElement(name = "CUST_CLUB_CODE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custclubcode;
    @XmlElement(name = "CUST_CLUB_NAME", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custclubname;
    @XmlElement(name = "CUST_CLUB_DESC", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custclubdesc;
    @XmlElement(name = "CUST_CLUB_TYPE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String custclubtype;
    @XmlElement(name = "EFF_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String effdate;
    @XmlElement(name = "EXP_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String expdate;
    @XmlElement(name = "STATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String state;
    @XmlElement(name = "STATE_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String statedate;
    @XmlElement(name = "CREATE_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String createdate;
    @XmlElement(name = "CUST_CLUB_MEMBER", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected List<CUSTCLUBMEMBER> custclubmember;
    @XmlElement(name = "MODIFY_DATE", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected String modifydate;
    @XmlAttribute(name = "ACTION_TYPE")
    protected String actiontype;

    /**
     * Gets the value of the custclubid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTCLUBID() {
        return custclubid;
    }

    /**
     * Sets the value of the custclubid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTCLUBID(String value) {
        this.custclubid = value;
    }

    /**
     * Gets the value of the custclubcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTCLUBCODE() {
        return custclubcode;
    }

    /**
     * Sets the value of the custclubcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTCLUBCODE(String value) {
        this.custclubcode = value;
    }

    /**
     * Gets the value of the custclubname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTCLUBNAME() {
        return custclubname;
    }

    /**
     * Sets the value of the custclubname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTCLUBNAME(String value) {
        this.custclubname = value;
    }

    /**
     * Gets the value of the custclubdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTCLUBDESC() {
        return custclubdesc;
    }

    /**
     * Sets the value of the custclubdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTCLUBDESC(String value) {
        this.custclubdesc = value;
    }

    /**
     * Gets the value of the custclubtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTCLUBTYPE() {
        return custclubtype;
    }

    /**
     * Sets the value of the custclubtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTCLUBTYPE(String value) {
        this.custclubtype = value;
    }

    /**
     * Gets the value of the effdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEFFDATE() {
        return effdate;
    }

    /**
     * Sets the value of the effdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEFFDATE(String value) {
        this.effdate = value;
    }

    /**
     * Gets the value of the expdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPDATE() {
        return expdate;
    }

    /**
     * Sets the value of the expdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPDATE(String value) {
        this.expdate = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATE() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATE(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the statedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATEDATE() {
        return statedate;
    }

    /**
     * Sets the value of the statedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATEDATE(String value) {
        this.statedate = value;
    }

    /**
     * Gets the value of the createdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATEDATE() {
        return createdate;
    }

    /**
     * Sets the value of the createdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATEDATE(String value) {
        this.createdate = value;
    }

    /**
     * Gets the value of the custclubmember property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the custclubmember property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCUSTCLUBMEMBER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CUSTCLUBMEMBER }
     * 
     * 
     */
    public List<CUSTCLUBMEMBER> getCUSTCLUBMEMBER() {
        if (custclubmember == null) {
            custclubmember = new ArrayList<CUSTCLUBMEMBER>();
        }
        return this.custclubmember;
    }

    /**
     * Gets the value of the modifydate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMODIFYDATE() {
        return modifydate;
    }

    /**
     * Sets the value of the modifydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMODIFYDATE(String value) {
        this.modifydate = value;
    }

    /**
     * Gets the value of the actiontype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTIONTYPE() {
        return actiontype;
    }

    /**
     * Sets the value of the actiontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTIONTYPE(String value) {
        this.actiontype = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.chinatelecom.com/crm/comm/}CUST_CLUB_MEMBER_TYPE">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CUSTCLUBMEMBER
        extends CUSTCLUBMEMBERTYPE
    {


    }

}
