//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//


package com.chinatelecom.www.crm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 客户归并输入
 * 
 * <p>Java class for MERGE_CUST_REQ_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MERGE_CUST_REQ_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PUB_RES" type="{http://www.chinatelecom.com/crm/comm/}PUB_RES_TYPE"/>
 *         &lt;element name="CUST_ID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="MERGERED_CUST_ID" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="50"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MERGE_CUST_REQ_TYPE", propOrder = {
    "pubres",
    "custid",
    "mergeredcustid"
})
public class MERGECUSTREQTYPE {

    @XmlElement(name = "PUB_RES", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected PUBRESTYPE pubres;
    @XmlElement(name = "CUST_ID", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected Object custid;
    @XmlElement(name = "MERGERED_CUST_ID", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected List<Object> mergeredcustid;

    /**
     * Gets the value of the pubres property.
     * 
     * @return
     *     possible object is
     *     {@link PUBRESTYPE }
     *     
     */
    public PUBRESTYPE getPUBRES() {
        return pubres;
    }

    /**
     * Sets the value of the pubres property.
     * 
     * @param value
     *     allowed object is
     *     {@link PUBRESTYPE }
     *     
     */
    public void setPUBRES(PUBRESTYPE value) {
        this.pubres = value;
    }

    /**
     * Gets the value of the custid property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCUSTID() {
        return custid;
    }

    /**
     * Sets the value of the custid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCUSTID(Object value) {
        this.custid = value;
    }

    /**
     * Gets the value of the mergeredcustid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mergeredcustid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMERGEREDCUSTID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getMERGEREDCUSTID() {
        if (mergeredcustid == null) {
            mergeredcustid = new ArrayList<Object>();
        }
        return this.mergeredcustid;
    }

}
