//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 ÏÂÎç CST 
//


package com.chinatelecom.www.crm;

import javax.xml.bind.annotation.XmlRegistry;
import com.chinatelecom.www.crm.CUSTCLUBTYPE.CUSTCLUBMEMBER;
import com.chinatelecom.www.crm.CUSTTYPEUP.CUSTCONTACTINFO;
import com.chinatelecom.www.crm.ContractRoot.SvcCont;
import com.chinatelecom.www.crm.QRYREQTYPE.QRYTYPE;
import com.chinatelecom.www.crm.QRYREQTYPE.QRYTYPE.PARAM;
import com.chinatelecom.www.crm.TcpCont.Request;
import com.chinatelecom.www.crm.TcpCont.Response;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.chinatelecom.www.crm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.chinatelecom.www.crm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContractRoot }
     * 
     */
    public ContractRoot createContractRoot() {
        return new ContractRoot();
    }

    /**
     * Create an instance of {@link SvcCont }
     * 
     */
    public SvcCont createContractRootSvcCont() {
        return new SvcCont();
    }

    /**
     * Create an instance of {@link QRYCUSTCERTREQTYPE }
     * 
     */
    public QRYCUSTCERTREQTYPE createQRYCUSTCERTREQTYPE() {
        return new QRYCUSTCERTREQTYPE();
    }

    /**
     * Create an instance of {@link CUSTCONTACTINFO }
     * 
     */
    public CUSTCONTACTINFO createCUSTTYPEUPCUSTCONTACTINFO() {
        return new CUSTCONTACTINFO();
    }

    /**
     * Create an instance of {@link CUSTATTRTYPE }
     * 
     */
    public CUSTATTRTYPE createCUSTATTRTYPE() {
        return new CUSTATTRTYPE();
    }

    /**
     * Create an instance of {@link QRYTEMPCUSTCREDITLIMITRESTYPE }
     * 
     */
    public QRYTEMPCUSTCREDITLIMITRESTYPE createQRYTEMPCUSTCREDITLIMITRESTYPE() {
        return new QRYTEMPCUSTCREDITLIMITRESTYPE();
    }

    /**
     * Create an instance of {@link PAYMENTPLANTYPE }
     * 
     */
    public PAYMENTPLANTYPE createPAYMENTPLANTYPE() {
        return new PAYMENTPLANTYPE();
    }

    /**
     * Create an instance of {@link QRYCUSATTRRESTYPE }
     * 
     */
    public QRYCUSATTRRESTYPE createQRYCUSATTRRESTYPE() {
        return new QRYCUSATTRRESTYPE();
    }

    /**
     * Create an instance of {@link QRYCUSTCERTRESTYPE }
     * 
     */
    public QRYCUSTCERTRESTYPE createQRYCUSTCERTRESTYPE() {
        return new QRYCUSTCERTRESTYPE();
    }

    /**
     * Create an instance of {@link CUSTCREDITTYPE }
     * 
     */
    public CUSTCREDITTYPE createCUSTCREDITTYPE() {
        return new CUSTCREDITTYPE();
    }

    /**
     * Create an instance of {@link ADDCUSTTEMPCREDITLIMITREQTYPE }
     * 
     */
    public ADDCUSTTEMPCREDITLIMITREQTYPE createADDCUSTTEMPCREDITLIMITREQTYPE() {
        return new ADDCUSTTEMPCREDITLIMITREQTYPE();
    }

    /**
     * Create an instance of {@link PARAM }
     * 
     */
    public PARAM createQRYREQTYPEQRYTYPEPARAM() {
        return new PARAM();
    }

    /**
     * Create an instance of {@link CUSTTYPEUP }
     * 
     */
    public CUSTTYPEUP createCUSTTYPEUP() {
        return new CUSTTYPEUP();
    }

    /**
     * Create an instance of {@link QRYCUSTCONTACTINFORESTYPE }
     * 
     */
    public QRYCUSTCONTACTINFORESTYPE createQRYCUSTCONTACTINFORESTYPE() {
        return new QRYCUSTCONTACTINFORESTYPE();
    }

    /**
     * Create an instance of {@link QRYPAYMENTPLANRESTYPE }
     * 
     */
    public QRYPAYMENTPLANRESTYPE createQRYPAYMENTPLANRESTYPE() {
        return new QRYPAYMENTPLANRESTYPE();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createTcpContResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link MODACCOUNTREQTYPE }
     * 
     */
    public MODACCOUNTREQTYPE createMODACCOUNTREQTYPE() {
        return new MODACCOUNTREQTYPE();
    }

    /**
     * Create an instance of {@link CUSTRELTYPE }
     * 
     */
    public CUSTRELTYPE createCUSTRELTYPE() {
        return new CUSTRELTYPE();
    }

    /**
     * Create an instance of {@link SAVEBILLFORMATCUSTOMIZEREQTYPE }
     * 
     */
    public SAVEBILLFORMATCUSTOMIZEREQTYPE createSAVEBILLFORMATCUSTOMIZEREQTYPE() {
        return new SAVEBILLFORMATCUSTOMIZEREQTYPE();
    }

    /**
     * Create an instance of {@link CUSTCREDITLOGTYPE }
     * 
     */
    public CUSTCREDITLOGTYPE createCUSTCREDITLOGTYPE() {
        return new CUSTCREDITLOGTYPE();
    }

    /**
     * Create an instance of {@link QRYCUSTRESTYPE }
     * 
     */
    public QRYCUSTRESTYPE createQRYCUSTRESTYPE() {
        return new QRYCUSTRESTYPE();
    }

    /**
     * Create an instance of {@link ADDTEMPCUSTCREDITLIMITRESTYPE }
     * 
     */
    public ADDTEMPCUSTCREDITLIMITRESTYPE createADDTEMPCUSTCREDITLIMITRESTYPE() {
        return new ADDTEMPCUSTCREDITLIMITRESTYPE();
    }

    /**
     * Create an instance of {@link MODCUSTREQTYPE }
     * 
     */
    public MODCUSTREQTYPE createMODCUSTREQTYPE() {
        return new MODCUSTREQTYPE();
    }

    /**
     * Create an instance of {@link QRYPAYMENTPLANREQTYPE }
     * 
     */
    public QRYPAYMENTPLANREQTYPE createQRYPAYMENTPLANREQTYPE() {
        return new QRYPAYMENTPLANREQTYPE();
    }

    /**
     * Create an instance of {@link CUSTCERTTYPE }
     * 
     */
    public CUSTCERTTYPE createCUSTCERTTYPE() {
        return new CUSTCERTTYPE();
    }

    /**
     * Create an instance of {@link QRYCUSTCREDITLOGRESTYPE }
     * 
     */
    public QRYCUSTCREDITLOGRESTYPE createQRYCUSTCREDITLOGRESTYPE() {
        return new QRYCUSTCREDITLOGRESTYPE();
    }

    /**
     * Create an instance of {@link QRYCUSTCREDITREQTYPE }
     * 
     */
    public QRYCUSTCREDITREQTYPE createQRYCUSTCREDITREQTYPE() {
        return new QRYCUSTCREDITREQTYPE();
    }

    /**
     * Create an instance of {@link QRYACCOUNTREQTYPE }
     * 
     */
    public QRYACCOUNTREQTYPE createQRYACCOUNTREQTYPE() {
        return new QRYACCOUNTREQTYPE();
    }

    /**
     * Create an instance of {@link ACCOUNTTYPE }
     * 
     */
    public ACCOUNTTYPE createACCOUNTTYPE() {
        return new ACCOUNTTYPE();
    }

    /**
     * Create an instance of {@link QRYCUSTATTRREQTYPE }
     * 
     */
    public QRYCUSTATTRREQTYPE createQRYCUSTATTRREQTYPE() {
        return new QRYCUSTATTRREQTYPE();
    }

    /**
     * Create an instance of {@link QRYRESTYPE }
     * 
     */
    public QRYRESTYPE createQRYRESTYPE() {
        return new QRYRESTYPE();
    }

    /**
     * Create an instance of {@link ADDCUSTREQTYPE }
     * 
     */
    public ADDCUSTREQTYPE createADDCUSTREQTYPE() {
        return new ADDCUSTREQTYPE();
    }

    /**
     * Create an instance of {@link ADDACCOUNTREQTYPE }
     * 
     */
    public ADDACCOUNTREQTYPE createADDACCOUNTREQTYPE() {
        return new ADDACCOUNTREQTYPE();
    }

    /**
     * Create an instance of {@link TcpCont }
     * 
     */
    public TcpCont createTcpCont() {
        return new TcpCont();
    }

    /**
     * Create an instance of {@link CUSTAUTHENTICATEREQTYPE }
     * 
     */
    public CUSTAUTHENTICATEREQTYPE createCUSTAUTHENTICATEREQTYPE() {
        return new CUSTAUTHENTICATEREQTYPE();
    }

    /**
     * Create an instance of {@link MERGECUSTREQTYPE }
     * 
     */
    public MERGECUSTREQTYPE createMERGECUSTREQTYPE() {
        return new MERGECUSTREQTYPE();
    }

    /**
     * Create an instance of {@link QRYACCOUNTRESTYPE }
     * 
     */
    public QRYACCOUNTRESTYPE createQRYACCOUNTRESTYPE() {
        return new QRYACCOUNTRESTYPE();
    }

    /**
     * Create an instance of {@link RULEEVENTINSTTYPE }
     * 
     */
    public RULEEVENTINSTTYPE createRULEEVENTINSTTYPE() {
        return new RULEEVENTINSTTYPE();
    }

    /**
     * Create an instance of {@link SAVECUSTATTRREQTYPE }
     * 
     */
    public SAVECUSTATTRREQTYPE createSAVECUSTATTRREQTYPE() {
        return new SAVECUSTATTRREQTYPE();
    }

    /**
     * Create an instance of {@link QRYCUSTRELRESTYPE }
     * 
     */
    public QRYCUSTRELRESTYPE createQRYCUSTRELRESTYPE() {
        return new QRYCUSTRELRESTYPE();
    }

    /**
     * Create an instance of {@link RULEEVENTINSTATTRTYPE }
     * 
     */
    public RULEEVENTINSTATTRTYPE createRULEEVENTINSTATTRTYPE() {
        return new RULEEVENTINSTATTRTYPE();
    }

    /**
     * Create an instance of {@link QRYTYPE }
     * 
     */
    public QRYTYPE createQRYREQTYPEQRYTYPE() {
        return new QRYTYPE();
    }

    /**
     * Create an instance of {@link DELCUSTRELREQTYPE }
     * 
     */
    public DELCUSTRELREQTYPE createDELCUSTRELREQTYPE() {
        return new DELCUSTRELREQTYPE();
    }

    /**
     * Create an instance of {@link CUSTCLUBMEMBER }
     * 
     */
    public CUSTCLUBMEMBER createCUSTCLUBTYPECUSTCLUBMEMBER() {
        return new CUSTCLUBMEMBER();
    }

    /**
     * Create an instance of {@link QRYCUSTTEMPCREDITLIMITREQTYPE }
     * 
     */
    public QRYCUSTTEMPCREDITLIMITREQTYPE createQRYCUSTTEMPCREDITLIMITREQTYPE() {
        return new QRYCUSTTEMPCREDITLIMITREQTYPE();
    }

    /**
     * Create an instance of {@link CUSTTYPE }
     * 
     */
    public CUSTTYPE createCUSTTYPE() {
        return new CUSTTYPE();
    }

    /**
     * Create an instance of {@link PUBRESTYPE }
     * 
     */
    public PUBRESTYPE createPUBRESTYPE() {
        return new PUBRESTYPE();
    }

    /**
     * Create an instance of {@link ADDCUSTRELREQTYPE }
     * 
     */
    public ADDCUSTRELREQTYPE createADDCUSTRELREQTYPE() {
        return new ADDCUSTRELREQTYPE();
    }

    /**
     * Create an instance of {@link ORDERREQTYPE }
     * 
     */
    public ORDERREQTYPE createORDERREQTYPE() {
        return new ORDERREQTYPE();
    }

    /**
     * Create an instance of {@link CREDITLIMITTYPE }
     * 
     */
    public CREDITLIMITTYPE createCREDITLIMITTYPE() {
        return new CREDITLIMITTYPE();
    }

    /**
     * Create an instance of {@link SAVEPAYMENTPLANREQTYPE }
     * 
     */
    public SAVEPAYMENTPLANREQTYPE createSAVEPAYMENTPLANREQTYPE() {
        return new SAVEPAYMENTPLANREQTYPE();
    }

    /**
     * Create an instance of {@link SAVECUSTCERTREQTYPE }
     * 
     */
    public SAVECUSTCERTREQTYPE createSAVECUSTCERTREQTYPE() {
        return new SAVECUSTCERTREQTYPE();
    }

    /**
     * Create an instance of {@link QRYCUSTCREDITLIMITREQTYPE }
     * 
     */
    public QRYCUSTCREDITLIMITREQTYPE createQRYCUSTCREDITLIMITREQTYPE() {
        return new QRYCUSTCREDITLIMITREQTYPE();
    }

    /**
     * Create an instance of {@link SAVECUSTCONTACTINFOREQTYPE }
     * 
     */
    public SAVECUSTCONTACTINFOREQTYPE createSAVECUSTCONTACTINFOREQTYPE() {
        return new SAVECUSTCONTACTINFOREQTYPE();
    }

    /**
     * Create an instance of {@link BILLFORMATCUSTOMIZETYPE }
     * 
     */
    public BILLFORMATCUSTOMIZETYPE createBILLFORMATCUSTOMIZETYPE() {
        return new BILLFORMATCUSTOMIZETYPE();
    }

    /**
     * Create an instance of {@link CUSTCLUBMEMBERTYPE }
     * 
     */
    public CUSTCLUBMEMBERTYPE createCUSTCLUBMEMBERTYPE() {
        return new CUSTCLUBMEMBERTYPE();
    }

    /**
     * Create an instance of {@link QRYCUSTREQTYPE }
     * 
     */
    public QRYCUSTREQTYPE createQRYCUSTREQTYPE() {
        return new QRYCUSTREQTYPE();
    }

    /**
     * Create an instance of {@link CUSTCERTIFICATIONTYPE }
     * 
     */
    public CUSTCERTIFICATIONTYPE createCUSTCERTIFICATIONTYPE() {
        return new CUSTCERTIFICATIONTYPE();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createTcpContRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link QRYCUSTRELREQTYPE }
     * 
     */
    public QRYCUSTRELREQTYPE createQRYCUSTRELREQTYPE() {
        return new QRYCUSTRELREQTYPE();
    }

    /**
     * Create an instance of {@link CUSTCLUBTYPE }
     * 
     */
    public CUSTCLUBTYPE createCUSTCLUBTYPE() {
        return new CUSTCLUBTYPE();
    }

    /**
     * Create an instance of {@link SAVECUSTCERTIFICATIONREQTYPE }
     * 
     */
    public SAVECUSTCERTIFICATIONREQTYPE createSAVECUSTCERTIFICATIONREQTYPE() {
        return new SAVECUSTCERTIFICATIONREQTYPE();
    }

    /**
     * Create an instance of {@link QRYCUSTCONTACTINFOREQTYPE }
     * 
     */
    public QRYCUSTCONTACTINFOREQTYPE createQRYCUSTCONTACTINFOREQTYPE() {
        return new QRYCUSTCONTACTINFOREQTYPE();
    }

    /**
     * Create an instance of {@link QRYREQTYPE }
     * 
     */
    public QRYREQTYPE createQRYREQTYPE() {
        return new QRYREQTYPE();
    }

    /**
     * Create an instance of {@link QRYCUSTCREDITLOGREQTYPE }
     * 
     */
    public QRYCUSTCREDITLOGREQTYPE createQRYCUSTCREDITLOGREQTYPE() {
        return new QRYCUSTCREDITLOGREQTYPE();
    }

    /**
     * Create an instance of {@link QRYCUSTCREDITLIMITRESTYPE }
     * 
     */
    public QRYCUSTCREDITLIMITRESTYPE createQRYCUSTCREDITLIMITRESTYPE() {
        return new QRYCUSTCREDITLIMITRESTYPE();
    }

    /**
     * Create an instance of {@link PUBREQTYPE }
     * 
     */
    public PUBREQTYPE createPUBREQTYPE() {
        return new PUBREQTYPE();
    }

    /**
     * Create an instance of {@link QRYCUSTCREDITRESTYPE }
     * 
     */
    public QRYCUSTCREDITRESTYPE createQRYCUSTCREDITRESTYPE() {
        return new QRYCUSTCREDITRESTYPE();
    }

    /**
     * Create an instance of {@link QRYBILLFORMATCUSTOMIZEREQTYPE }
     * 
     */
    public QRYBILLFORMATCUSTOMIZEREQTYPE createQRYBILLFORMATCUSTOMIZEREQTYPE() {
        return new QRYBILLFORMATCUSTOMIZEREQTYPE();
    }

    /**
     * Create an instance of {@link CUSTCONTACTINFOTYPE }
     * 
     */
    public CUSTCONTACTINFOTYPE createCUSTCONTACTINFOTYPE() {
        return new CUSTCONTACTINFOTYPE();
    }

    /**
     * Create an instance of {@link QRYBILLFORMATCUSTOMIZERESTYPE }
     * 
     */
    public QRYBILLFORMATCUSTOMIZERESTYPE createQRYBILLFORMATCUSTOMIZERESTYPE() {
        return new QRYBILLFORMATCUSTOMIZERESTYPE();
    }

}
