//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 обнГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.chinatelecom.com/crm/comm/")
package com.chinatelecom.www.crm;
