//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//


package com.chinatelecom.www.crm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 支付方案类型
 * 
 * <p>Java class for PAYMENT_PLAN_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PAYMENT_PLAN_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PAYMENT_PLAN_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ACCOUNT_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PAYMENT_METHOD_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PAYMENT_BANK_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PAYMENT_ACCOUNT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PAYMENT_ACCOUNT_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PAYMENT_ACCOUNT_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRIORITY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STATUS_CD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STATUS_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PAYMENT_PLAN_TYPE", propOrder = {
    "paymentplanid",
    "accountid",
    "paymentmethodid",
    "paymentbankid",
    "paymentaccount",
    "paymentaccountname",
    "paymentaccounttype",
    "priority",
    "statuscd",
    "statusdate"
})
public class PAYMENTPLANTYPE {

    @XmlElement(name = "PAYMENT_PLAN_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String paymentplanid;
    @XmlElement(name = "ACCOUNT_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String accountid;
    @XmlElement(name = "PAYMENT_METHOD_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String paymentmethodid;
    @XmlElement(name = "PAYMENT_BANK_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String paymentbankid;
    @XmlElement(name = "PAYMENT_ACCOUNT", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String paymentaccount;
    @XmlElement(name = "PAYMENT_ACCOUNT_NAME", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String paymentaccountname;
    @XmlElement(name = "PAYMENT_ACCOUNT_TYPE", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected String paymentaccounttype;
    @XmlElement(name = "PRIORITY", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String priority;
    @XmlElement(name = "STATUS_CD", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String statuscd;
    @XmlElement(name = "STATUS_DATE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String statusdate;

    /**
     * Gets the value of the paymentplanid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYMENTPLANID() {
        return paymentplanid;
    }

    /**
     * Sets the value of the paymentplanid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYMENTPLANID(String value) {
        this.paymentplanid = value;
    }

    /**
     * Gets the value of the accountid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCOUNTID() {
        return accountid;
    }

    /**
     * Sets the value of the accountid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCOUNTID(String value) {
        this.accountid = value;
    }

    /**
     * Gets the value of the paymentmethodid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYMENTMETHODID() {
        return paymentmethodid;
    }

    /**
     * Sets the value of the paymentmethodid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYMENTMETHODID(String value) {
        this.paymentmethodid = value;
    }

    /**
     * Gets the value of the paymentbankid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYMENTBANKID() {
        return paymentbankid;
    }

    /**
     * Sets the value of the paymentbankid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYMENTBANKID(String value) {
        this.paymentbankid = value;
    }

    /**
     * Gets the value of the paymentaccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYMENTACCOUNT() {
        return paymentaccount;
    }

    /**
     * Sets the value of the paymentaccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYMENTACCOUNT(String value) {
        this.paymentaccount = value;
    }

    /**
     * Gets the value of the paymentaccountname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYMENTACCOUNTNAME() {
        return paymentaccountname;
    }

    /**
     * Sets the value of the paymentaccountname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYMENTACCOUNTNAME(String value) {
        this.paymentaccountname = value;
    }

    /**
     * Gets the value of the paymentaccounttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYMENTACCOUNTTYPE() {
        return paymentaccounttype;
    }

    /**
     * Sets the value of the paymentaccounttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYMENTACCOUNTTYPE(String value) {
        this.paymentaccounttype = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRIORITY() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRIORITY(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the statuscd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSCD() {
        return statuscd;
    }

    /**
     * Sets the value of the statuscd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSCD(String value) {
        this.statuscd = value;
    }

    /**
     * Gets the value of the statusdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSDATE() {
        return statusdate;
    }

    /**
     * Sets the value of the statusdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSDATE(String value) {
        this.statusdate = value;
    }

}
