//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//


package com.chinatelecom.www.crm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.chinatelecom.www.crm.QRYREQTYPE.QRYTYPE;
import com.chinatelecom.www.crm.QRYREQTYPE.QRYTYPE.PARAM;


/**
 * 查询通用输入
 * 
 * <p>Java class for QRY_REQ_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QRY_REQ_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FIELD" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="QRY_TYPE" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PARAM" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="PARAM_CD" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="PARAM_VALUE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="TYPE_CD" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PAGE_INDEX" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PAGE_SIZE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QRY_REQ_TYPE", propOrder = {
    "field",
    "qrytype",
    "pageindex",
    "pagesize"
})
public class QRYREQTYPE {

    @XmlElement(name = "FIELD", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected List<Object> field;
    @XmlElement(name = "QRY_TYPE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected QRYTYPE qrytype;
    @XmlElement(name = "PAGE_INDEX", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String pageindex;
    @XmlElement(name = "PAGE_SIZE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String pagesize;

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFIELD().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getFIELD() {
        if (field == null) {
            field = new ArrayList<Object>();
        }
        return this.field;
    }

    /**
     * Gets the value of the qrytype property.
     * 
     * @return
     *     possible object is
     *     {@link QRYTYPE }
     *     
     */
    public QRYTYPE getQRYTYPE() {
        return qrytype;
    }

    /**
     * Sets the value of the qrytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link QRYTYPE }
     *     
     */
    public void setQRYTYPE(QRYTYPE value) {
        this.qrytype = value;
    }

    /**
     * Gets the value of the pageindex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAGEINDEX() {
        return pageindex;
    }

    /**
     * Sets the value of the pageindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAGEINDEX(String value) {
        this.pageindex = value;
    }

    /**
     * Gets the value of the pagesize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAGESIZE() {
        return pagesize;
    }

    /**
     * Sets the value of the pagesize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAGESIZE(String value) {
        this.pagesize = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PARAM" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="PARAM_CD" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="PARAM_VALUE" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="TYPE_CD" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "param"
    })
    public static class QRYTYPE {

        @XmlElement(name = "PARAM", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
        protected List<PARAM> param;
        @XmlAttribute(name = "TYPE_CD")
        protected String typecd;

        /**
         * Gets the value of the param property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the param property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPARAM().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PARAM }
         * 
         * 
         */
        public List<PARAM> getPARAM() {
            if (param == null) {
                param = new ArrayList<PARAM>();
            }
            return this.param;
        }

        /**
         * Gets the value of the typecd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTYPECD() {
            return typecd;
        }

        /**
         * Sets the value of the typecd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTYPECD(String value) {
            this.typecd = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="PARAM_CD" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="PARAM_VALUE" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class PARAM {

            @XmlAttribute(name = "PARAM_CD")
            protected String paramcd;
            @XmlAttribute(name = "PARAM_VALUE")
            protected String paramvalue;

            /**
             * Gets the value of the paramcd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPARAMCD() {
                return paramcd;
            }

            /**
             * Sets the value of the paramcd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPARAMCD(String value) {
                this.paramcd = value;
            }

            /**
             * Gets the value of the paramvalue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPARAMVALUE() {
                return paramvalue;
            }

            /**
             * Sets the value of the paramvalue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPARAMVALUE(String value) {
                this.paramvalue = value;
            }

        }

    }

}
