//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//


package com.chinatelecom.www.crm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 规则事件实例属性
 * 
 * <p>Java class for RULE_EVENT_INST_ATTR_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RULE_EVENT_INST_ATTR_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RULE_EVENT_INST_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ATTR_CD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ATTR_VALUE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RULE_EVENT_INST_ATTR_TYPE", propOrder = {
    "ruleeventinstid",
    "attrcd",
    "attrvalue"
})
public class RULEEVENTINSTATTRTYPE {

    @XmlElement(name = "RULE_EVENT_INST_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String ruleeventinstid;
    @XmlElement(name = "ATTR_CD", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String attrcd;
    @XmlElement(name = "ATTR_VALUE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String attrvalue;

    /**
     * Gets the value of the ruleeventinstid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRULEEVENTINSTID() {
        return ruleeventinstid;
    }

    /**
     * Sets the value of the ruleeventinstid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRULEEVENTINSTID(String value) {
        this.ruleeventinstid = value;
    }

    /**
     * Gets the value of the attrcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getATTRCD() {
        return attrcd;
    }

    /**
     * Sets the value of the attrcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setATTRCD(String value) {
        this.attrcd = value;
    }

    /**
     * Gets the value of the attrvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getATTRVALUE() {
        return attrvalue;
    }

    /**
     * Sets the value of the attrvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setATTRVALUE(String value) {
        this.attrvalue = value;
    }

}
