//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//


package com.chinatelecom.www.crm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 规则事件实例
 * 
 * <p>Java class for RULE_EVENT_INST_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RULE_EVENT_INST_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RULE_EVENT_INST_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RULE_EVENT_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RULE_EVENT_NBR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RSP_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RSP_DESC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RULE_EVEN_INST_ATTR" type="{http://www.chinatelecom.com/crm/comm/}RULE_EVENT_INST_ATTR_TYPE" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RULE_EVENT_INST_TYPE", propOrder = {
    "ruleeventinstid",
    "ruleeventid",
    "ruleeventnbr",
    "rspcode",
    "rspdesc",
    "ruleeveninstattr"
})
public class RULEEVENTINSTTYPE {

    @XmlElement(name = "RULE_EVENT_INST_ID", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected String ruleeventinstid;
    @XmlElement(name = "RULE_EVENT_ID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String ruleeventid;
    @XmlElement(name = "RULE_EVENT_NBR", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String ruleeventnbr;
    @XmlElement(name = "RSP_CODE", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String rspcode;
    @XmlElement(name = "RSP_DESC", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String rspdesc;
    @XmlElement(name = "RULE_EVEN_INST_ATTR", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected List<RULEEVENTINSTATTRTYPE> ruleeveninstattr;

    /**
     * Gets the value of the ruleeventinstid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRULEEVENTINSTID() {
        return ruleeventinstid;
    }

    /**
     * Sets the value of the ruleeventinstid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRULEEVENTINSTID(String value) {
        this.ruleeventinstid = value;
    }

    /**
     * Gets the value of the ruleeventid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRULEEVENTID() {
        return ruleeventid;
    }

    /**
     * Sets the value of the ruleeventid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRULEEVENTID(String value) {
        this.ruleeventid = value;
    }

    /**
     * Gets the value of the ruleeventnbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRULEEVENTNBR() {
        return ruleeventnbr;
    }

    /**
     * Sets the value of the ruleeventnbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRULEEVENTNBR(String value) {
        this.ruleeventnbr = value;
    }

    /**
     * Gets the value of the rspcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRSPCODE() {
        return rspcode;
    }

    /**
     * Sets the value of the rspcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRSPCODE(String value) {
        this.rspcode = value;
    }

    /**
     * Gets the value of the rspdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRSPDESC() {
        return rspdesc;
    }

    /**
     * Sets the value of the rspdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRSPDESC(String value) {
        this.rspdesc = value;
    }

    /**
     * Gets the value of the ruleeveninstattr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ruleeveninstattr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRULEEVENINSTATTR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RULEEVENTINSTATTRTYPE }
     * 
     * 
     */
    public List<RULEEVENTINSTATTRTYPE> getRULEEVENINSTATTR() {
        if (ruleeveninstattr == null) {
            ruleeveninstattr = new ArrayList<RULEEVENTINSTATTRTYPE>();
        }
        return this.ruleeveninstattr;
    }

}
