//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//

package com.chinatelecom.www.crm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 保存客户联系信息输入
 * 
 * <p>Java class for SAVE_CUST_CONTACT_INFO_REQ_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SAVE_CUST_CONTACT_INFO_REQ_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PUB_REQ" type="{http://www.chinatelecom.com/crm/comm/}PUB_REQ_TYPE"/>
 *         &lt;element name="CUST_CONTACT" type="{http://www.chinatelecom.com/crm/comm/}CUST_CONTACT_INFO_TYPE" maxOccurs="50"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SAVE_CUST_CONTACT_INFO_REQ_TYPE", propOrder = { "pubreq", "custcontact" })
@XmlRootElement(name = "SAVECUSTCONTACTINFOREQTYPE")
public class SAVECUSTCONTACTINFOREQTYPE {

	@XmlElement(name = "PUB_REQ", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
	protected PUBREQTYPE pubreq;
	@XmlElement(name = "CUST_CONTACT", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
	protected List<CUSTCONTACTINFOTYPE> custcontact;

	/**
	 * Gets the value of the pubreq property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link PUBREQTYPE }
	 *     
	 */
	public PUBREQTYPE getPUBREQ() {
		return pubreq;
	}

	/**
	 * Sets the value of the pubreq property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link PUBREQTYPE }
	 *     
	 */
	public void setPUBREQ(PUBREQTYPE value) {
		this.pubreq = value;
	}

	/**
	 * Gets the value of the custcontact property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the custcontact property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getCUSTCONTACT().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link CUSTCONTACTINFOTYPE }
	 * 
	 * 
	 */
	public List<CUSTCONTACTINFOTYPE> getCUSTCONTACT() {
		if (custcontact == null) {
			custcontact = new ArrayList<CUSTCONTACTINFOTYPE>();
		}
		return this.custcontact;
	}

}
