//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//


package com.chinatelecom.www.crm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 保存支付方案输入
 * 
 * <p>Java class for SAVE_PAYMENT_PLAN_REQ_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SAVE_PAYMENT_PLAN_REQ_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PUB_REQ" type="{http://www.chinatelecom.com/crm/comm/}PUB_REQ_TYPE"/>
 *         &lt;element name="PAYMENT_PLAN" type="{http://www.chinatelecom.com/crm/comm/}PAYMENT_PLAN_TYPE" maxOccurs="50"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SAVE_PAYMENT_PLAN_REQ_TYPE", propOrder = {
    "pubreq",
    "paymentplan"
})
public class SAVEPAYMENTPLANREQTYPE {

    @XmlElement(name = "PUB_REQ", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected PUBREQTYPE pubreq;
    @XmlElement(name = "PAYMENT_PLAN", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected List<PAYMENTPLANTYPE> paymentplan;

    /**
     * Gets the value of the pubreq property.
     * 
     * @return
     *     possible object is
     *     {@link PUBREQTYPE }
     *     
     */
    public PUBREQTYPE getPUBREQ() {
        return pubreq;
    }

    /**
     * Sets the value of the pubreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PUBREQTYPE }
     *     
     */
    public void setPUBREQ(PUBREQTYPE value) {
        this.pubreq = value;
    }

    /**
     * Gets the value of the paymentplan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentplan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPAYMENTPLAN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PAYMENTPLANTYPE }
     * 
     * 
     */
    public List<PAYMENTPLANTYPE> getPAYMENTPLAN() {
        if (paymentplan == null) {
            paymentplan = new ArrayList<PAYMENTPLANTYPE>();
        }
        return this.paymentplan;
    }

}
