//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 01:43:57 下午 CST 
//


package com.chinatelecom.www.crm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.chinatelecom.www.crm.TcpCont.Request;
import com.chinatelecom.www.crm.TcpCont.Response;


/**
 * 控制对象
 * 
 * <p>Java class for TcpCont complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TcpCont">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="28"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ActionCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BusCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ServiceCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ServiceContractVer" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="16"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ServiceLevel" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SrcOrgID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SrcSysID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SrcSysSign" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="128"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DstOrgID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DstSysID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ReqTime" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RspTime" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Request" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ReqType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ReqCode">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="4"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ReqDesc" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="0"/>
 *                         &lt;maxLength value="128"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Response" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RspType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="14"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RspCode">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="14"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RspDesc" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="14"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TcpCont", propOrder = {
    "transactionID",
    "actionCode",
    "busCode",
    "serviceCode",
    "serviceContractVer",
    "serviceLevel",
    "srcOrgID",
    "srcSysID",
    "srcSysSign",
    "dstOrgID",
    "dstSysID",
    "reqTime",
    "rspTime",
    "request",
    "response"
})
public class TcpCont {

    @XmlElement(name = "TransactionID", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected String transactionID;
    @XmlElement(name = "ActionCode", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected String actionCode;
    @XmlElement(name = "BusCode", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String busCode;
    @XmlElement(name = "ServiceCode", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String serviceCode;
    @XmlElement(name = "ServiceContractVer", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String serviceContractVer;
    @XmlElement(name = "ServiceLevel", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String serviceLevel;
    @XmlElement(name = "SrcOrgID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String srcOrgID;
    @XmlElement(name = "SrcSysID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String srcSysID;
    @XmlElement(name = "SrcSysSign", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String srcSysSign;
    @XmlElement(name = "DstOrgID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String dstOrgID;
    @XmlElement(name = "DstSysID", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String dstSysID;
    @XmlElement(name = "ReqTime", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String reqTime;
    @XmlElement(name = "RspTime", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected String rspTime;
    @XmlElement(name = "Request", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
    protected List<Request> request;
    @XmlElement(name = "Response", namespace = "http://www.chinatelecom.com/crm/comm/")
    protected Response response;

    /**
     * Gets the value of the transactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionID() {
        return transactionID;
    }

    /**
     * Sets the value of the transactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionID(String value) {
        this.transactionID = value;
    }

    /**
     * Gets the value of the actionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionCode() {
        return actionCode;
    }

    /**
     * Sets the value of the actionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionCode(String value) {
        this.actionCode = value;
    }

    /**
     * Gets the value of the busCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusCode() {
        return busCode;
    }

    /**
     * Sets the value of the busCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusCode(String value) {
        this.busCode = value;
    }

    /**
     * Gets the value of the serviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceCode(String value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the serviceContractVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceContractVer() {
        return serviceContractVer;
    }

    /**
     * Sets the value of the serviceContractVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceContractVer(String value) {
        this.serviceContractVer = value;
    }

    /**
     * Gets the value of the serviceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceLevel() {
        return serviceLevel;
    }

    /**
     * Sets the value of the serviceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceLevel(String value) {
        this.serviceLevel = value;
    }

    /**
     * Gets the value of the srcOrgID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcOrgID() {
        return srcOrgID;
    }

    /**
     * Sets the value of the srcOrgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcOrgID(String value) {
        this.srcOrgID = value;
    }

    /**
     * Gets the value of the srcSysID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcSysID() {
        return srcSysID;
    }

    /**
     * Sets the value of the srcSysID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcSysID(String value) {
        this.srcSysID = value;
    }

    /**
     * Gets the value of the srcSysSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcSysSign() {
        return srcSysSign;
    }

    /**
     * Sets the value of the srcSysSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcSysSign(String value) {
        this.srcSysSign = value;
    }

    /**
     * Gets the value of the dstOrgID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDstOrgID() {
        return dstOrgID;
    }

    /**
     * Sets the value of the dstOrgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDstOrgID(String value) {
        this.dstOrgID = value;
    }

    /**
     * Gets the value of the dstSysID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDstSysID() {
        return dstSysID;
    }

    /**
     * Sets the value of the dstSysID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDstSysID(String value) {
        this.dstSysID = value;
    }

    /**
     * Gets the value of the reqTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqTime() {
        return reqTime;
    }

    /**
     * Sets the value of the reqTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqTime(String value) {
        this.reqTime = value;
    }

    /**
     * Gets the value of the rspTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRspTime() {
        return rspTime;
    }

    /**
     * Sets the value of the rspTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRspTime(String value) {
        this.rspTime = value;
    }

    /**
     * Gets the value of the request property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the request property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Request }
     * 
     * 
     */
    public List<Request> getRequest() {
        if (request == null) {
            request = new ArrayList<Request>();
        }
        return this.request;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setResponse(Response value) {
        this.response = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ReqType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ReqCode">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="4"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ReqDesc" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="0"/>
     *               &lt;maxLength value="128"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reqType",
        "reqCode",
        "reqDesc"
    })
    public static class Request {

        @XmlElement(name = "ReqType", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
        protected String reqType;
        @XmlElement(name = "ReqCode", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
        protected String reqCode;
        @XmlElement(name = "ReqDesc", namespace = "http://www.chinatelecom.com/crm/comm/")
        protected String reqDesc;

        /**
         * Gets the value of the reqType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReqType() {
            return reqType;
        }

        /**
         * Sets the value of the reqType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReqType(String value) {
            this.reqType = value;
        }

        /**
         * Gets the value of the reqCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReqCode() {
            return reqCode;
        }

        /**
         * Sets the value of the reqCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReqCode(String value) {
            this.reqCode = value;
        }

        /**
         * Gets the value of the reqDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReqDesc() {
            return reqDesc;
        }

        /**
         * Sets the value of the reqDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReqDesc(String value) {
            this.reqDesc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RspType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="14"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RspCode">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="14"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RspDesc" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="14"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rspType",
        "rspCode",
        "rspDesc"
    })
    public static class Response {

        @XmlElement(name = "RspType", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
        protected String rspType;
        @XmlElement(name = "RspCode", namespace = "http://www.chinatelecom.com/crm/comm/", required = true)
        protected String rspCode;
        @XmlElement(name = "RspDesc", namespace = "http://www.chinatelecom.com/crm/comm/")
        protected String rspDesc;

        /**
         * Gets the value of the rspType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRspType() {
            return rspType;
        }

        /**
         * Sets the value of the rspType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRspType(String value) {
            this.rspType = value;
        }

        /**
         * Gets the value of the rspCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRspCode() {
            return rspCode;
        }

        /**
         * Sets the value of the rspCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRspCode(String value) {
            this.rspCode = value;
        }

        /**
         * Gets the value of the rspDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRspDesc() {
            return rspDesc;
        }

        /**
         * Sets the value of the rspDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRspDesc(String value) {
            this.rspDesc = value;
        }

    }

}
